timezone: America/Los_Angeles
encoding: utf-8

author: Shane
site_name: CSSNR GitHub Pages
site_url: https://cssnr.github.io

github_url: https://github.com/cssnr

discord_webhook: https://discord.com/api/webhooks/242137648028712961/4xM7SXClH_i8we_epG6AXMaqhueg5L5oAVf1dnLw1_el05OxZ-JVfph-QrcQwPkOMJem
