timezone: America/Los_Angeles
encoding: utf-8

url: https://cssnr.github.io

author: Shane
site_name: CSSNR GitHub Pages

menu:
  - name: Home
    link: /
  - name: About
    link: /about/
  - name: Feedback
    link: /feedback/

github_url: https://github.com/cssnr

discord_invite: https://discord.gg/wXy6m2X8wY
discord_webhook: https://discord.com/api/webhooks/1258944618389569566/gqge0T5UZcJHLxfAFLPNjlzsuqikQJtTlCRvVWbw2ufDv_WrJ8yzVRWenb__s1PxyawH
