timezone: America/Los_Angeles
encoding: utf-8

url: https://cssnr.github.io

author: Shane
site_name: CSSNR

menu:
  - name: Home
    link: /
  - name: About
    link: /about/
  - name: Feedback
    link: /feedback/
  - name: Support
    link: https://ko-fi.com/cssnr
    external: true

github_url: https://github.com/cssnr
discord_invite: https://discord.gg/wXy6m2X8wY
relay_url: https://relay.cssnr.com/discord/1258944618389569566
