name: "Pages"

on:
  push:
    branches: [master]
    paths:
      - ".github/workflows/pages.yaml"
      - "src/**"
      - "gulpfile.js"
      - "package*.json"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    name: "Build"
    uses: ./.github/workflows/docs.yaml
    secrets: inherit
    permissions:
      contents: read

  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: "Deploy Pages"
        id: deployment
        uses: actions/deploy-pages@v4

      - name: "Send Notification"
        if: ${{ !cancelled() }}
        continue-on-error: true
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          description: ${{ steps.deployment.outputs.page_url }}
