name: "Pages"

on:
  push:
    branches:
      - "master"
    paths:
      - "src/**"
      - "gulpfile.js"
      - "package.json"
      - ".github/workflows/pages.yaml"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "Setup Node 22"
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: "Install Dependencies"
        run: |
          npm ci

      #- name: "Update Cache Version"
      #  run: |
      #    echo "Updating Cache to Version: v${GITHUB_RUN_NUMBER}"
      #    sed -i "0,/v1/s//v${GITHUB_RUN_NUMBER}/" src/sw.js
      #    head src/sw.js -n 4

      - name: "Configure Pages"
        uses: actions/configure-pages@v5

      - name: "Jekyll Build Pages"
        uses: actions/jekyll-build-pages@v1
        with:
          source: "./src"

      - name: "Upload Pages Artifact"
        uses: actions/upload-pages-artifact@v4
        with:
          path: _site/

      - name: "Send Failure Notification"
        if: ${{ failure() }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}

  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: "Deploy Pages"
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages

      - name: "Send Deploy Notification"
        if: ${{ !cancelled() }}
        continue-on-error: true
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
